# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f79f4e8350c3274e34297330e47908590c13349854e24a0cfede780af1d953d96c3a5508073e6b6612c0d13a4b8fbe5e8e2edf7dd822fd9c5a72f66b6f967e6a

test:
  secret_key_base: 34732bcba942299314f437748b02d5071ffb3060329ea8b397fcbe5c58985aa7b45206abab2954637a72bd5659521c4113668c6ba587e7718115b1dc701a75fe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
