#encoding: utf-8
Static.create(title: "Акции", short_url: "special")
Static.create(title: "Доставка и оплата", short_url: "shipping_and_payment")
Static.create(title: "Пиццерия", short_url: "about")

Product.create(name: "Маргарита", description: "Красный соус, помидоры, моцарелла", category_id: 1)
Product.create(name: "Дары моря", description: "Красный соус, мидии, креветки, семга, оливки, моцарелла", category_id: 1)
Product.create(name: "Мясное ассорти", description: "Красный соус, свинина, курица, колбаса п/к, бекон, охотничьи колбаски, помидоры, моцарелла", category_id: 1)
Product.create(name: "Пепперони", description: "Красный соус , пепперони, моцарелла", category_id: 1)
Product.create(name: "Карбонара", description: "Белый соус, бекон, яйцо, лук, моцарелла", category_id: 1)
Product.create(name: "Гавайи", description: "Красный соус, курица, ананас, моцарелла", category_id: 1)
Product.create(name: "4 сыра", description: "Красный соус, дор-блю, пармезан, гауда, моцарелла", category_id: 1)
Product.create(name: "Вегетарианская", description: "Красный соус, цукини, баклажаны, шампиньоны, Красный лук, перец болгарский, брокколи, оливки, моцарелла", category_id: 1)
Product.create(name: "Инь-янь", description: "Красный и белый соус, кпченая курица, помидоры, колбаса п/к, моцарелла", category_id: 1)
Product.create(name: "Гранд-корне", description: "Красный соус, пеперони, ветчина, колбаса п/к, охотничьи колбаски, моцарелла", category_id: 1)
Product.create(name: "Ностро азуро (острая)", description: "Красный соус, пеперони, охотничьи клбаски, оливки, аджика, брынза, моцарелла", category_id: 1)
Product.create(name: "Деревенская", description: "Соус сметано-горчичный, сосиски, грибы, свинина, помидоры, моцарелла", category_id: 1)
Product.create(name: "Цезарь", description: "Белый соус, курица, лист салата, помидоры, пармезан, моцарелла", category_id: 1)
Product.create(name: "Креветки руккола", description: "Красный соус, королевские креветки, руккола, моцарелла", category_id: 1)
Product.create(name: "Лючия", description: "Красный соус, колбаса п/к, корнишоны, курица, болгарский перец, помидоры, моцарелла", category_id: 1)
Product.create(name: "Brothers", description: "Белый соус, колбаса п/к, корнишоны, свинина, помидоры, брокколи, моцарелла", category_id: 1)
Product.create(name: "Американ-дрим", description: "Белый соус, шампиньоны, помидоры, курица, бекон, чеснок, моцарелла", category_id: 1)
Product.create(name: "Алькапоне", description: "Белый соус, свинина, курица, бекон, перец болгарский, помидоры, шампиньоны, моцарелла", category_id: 1)
Product.create(name: "Брезаола", description: "Красный соус, ветчина, грибы, моцарелла", category_id: 1)
Product.create(name: "Феррари", description: "Красный соус, свинина, курица, болгарский перец, моцарелла", category_id: 1)

Product.create(name: "Греческий", description: "Помидоры, огурцы, болгарский перец, оливки, кр.лук, брынза, оливковое масло", category_id: 2)
Product.create(name: "Цезарь с курицей", description: "Куриная грудка, айсберг, пекинская капуста, помидоры, сыр пармезан, соус Цезарь, гренки", category_id: 2)
Product.create(name: "Цезарь с креветками", description: "Креветки, айсберг, пекинская капуста, сыр пармезан, соус Цезарь, гренки", category_id: 2)
Product.create(name: "Моцарелла с помидорами", description: "Помидоры, маццарелла, соус Песто", category_id: 2)
Product.create(name: "Руккола с креветками в медово-горчичном соусе", description: "Креветки, руккола, соус медово-горчичный", category_id: 2)
Product.create(name: "Помидоры с красным луком и черным перцем", description: "Помидоры, красный лук, черный молотый перец, оливковое масло", category_id: 2)
Product.create(name: "Роллы Калифорния №1", description: "Снежный краб, огурец, авокадо, майонез, кунжут", category_id: 2)
Product.create(name: "Калифорния №2", description: "Снежный краб, майонез, авокадо, икра тобика", category_id: 2)
Product.create(name: "Филадельфия", description: "Лосось с/с, авокадо, сыр", category_id: 2)
Product.create(name: "Авокадо ролл", description: "Авокадо", category_id: 2)
Product.create(name: "Ролл Хокайдо", description: "Копченый лосось, снежный краб, сыр, кужут", category_id: 2)
Product.create(name: "Цезарь ролл", description: "Курица, пекинская капуста, соус Цезарь, сыр пармезан", category_id: 2)
Product.create(name: "Сяке маки", description: "Лосось с/c", category_id: 2)
Product.create(name: "Кунсей темпура ролл", description: "Копченый лосось, сыр, обжренные в панировке", category_id: 2)
Product.create(name: "Сяке кунсей маки", description: "Копченый лосось", category_id: 2)
Product.create(name: "Огуно наки", description: "Огурец, кунжут", category_id: 2)
Product.create(name: "Эби маки", description: "Тигровая креветка", category_id: 2)
Product.create(name: "Эби темпура маки", description: "Креветка, салат айсберг, сыр, обжаренные в панировке", category_id: 2)
Product.create(name: "Аляска ролл", description: "Лосось с/с, авокадо, снежный краб, сыр, кунжут", category_id: 2)
Product.create(name: "Фантазия", description: "Лосось с/с, яблоко, сыр", category_id: 2)
Product.create(name: "Спайс угорь", description: "Угорь, огурец, кунжут", category_id: 2)
Product.create(name: "СУШИ Сяке", description: "Слабосоленый лосось", category_id: 2)
Product.create(name: "Кунсей", description: "Копченый лосось", category_id: 2)
Product.create(name: "Унаги", description: "Угорь", category_id: 2)
Product.create(name: "Эби", description: "Тигровая креветка", category_id: 2)
Product.create(name: "Ика", description: "Кальмар", category_id: 2)
Product.create(name: "Спайс сяке", description: "Лосось", category_id: 2)
Product.create(name: "Спайс сяке кунсей", description: "Копченый лосось", category_id: 2)
Product.create(name: "Спайс унаги", description: "Угорь", category_id: 2)
Product.create(name: "Спайс эби", description: "Тигровая креветка", category_id: 2)
Product.create(name: "Спайс ика", description: "Кальмар", category_id: 2)
Product.create(name: "Кани спайс", description: "Краб", category_id: 2)